words = [
    "aegis",
    "alchemist",
    "arsenal",
    "assassin",
    "avenger",
    "berserker",
    "bulwark",
    "chronomancer",
    "demon-hunter",
    "demonologist",
    "dragon-rider",
    "drifter",
    "druid",
    "equinox",
    "gravewalker",
    "gunslinger",
    "hexblade",
    "knightmare",
    "lifeweaver",
    "paladin",
    "phoenix",
    "riftblade",
    "rimeguard",
    "seeker",
    "shadebinder",
    "shadow-dancer",
    "shapeshifter",
    "skald",
    "thunderclaw",
    "tidecaller",
    "valkyrie",
    "warden",
    "warlord",
]

for word in words:
    print(f"- {word.capitalize()}: {word}.md")
